Description: >
    Adrian Peña / Udacity
    Create infrastructure for cluster

Resources:
    myCluster:
      Type: 'AWS::EKS::Cluster'
      Properties:
        Name: hello-node-cluster
        Version: '1.14'
        RoleArn: >-
            arn:aws:iam::518576844828:role/eksrole
        ResourcesVpcConfig:
          SecurityGroupIds:
            - sg-03ac92ba2c00544fb
          SubnetIds:
            - subnet-01c8de1d7645152f3
            - subnet-0a813311ee7f06785
            - subnet-00e910698fd59a460